# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-23 01:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tweetApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweetmodel',
            name='contentLimited',
        ),
        migrations.AddField(
            model_name='tweetmodel',
            name='dataCreated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tweetmodel',
            name='dataUpdated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
