# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-23 01:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweetApp', '0002_auto_20180123_0716'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TweetModel',
            new_name='Tweet',
        ),
    ]
