# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-11 08:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usersApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='followers',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='followers',
            name='follow',
        ),
        migrations.AddField(
            model_name='followers',
            name='follow',
            field=models.ManyToManyField(related_name='followed_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
